// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "StutterGuide",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "StutterGuide",
            targets: ["AppModule"],
            bundleIdentifier: "com.mohalibou.StutterGuide",
            teamIdentifier: "4UD8YB3K7V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .butterfly),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "StutterGuide uses speech recognition to transcribe your practice and coach smooth speech."),
                .microphone(purposeString: "StutterGuide uses your microphone to listen as you practice speaking.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
